"use client";

import { motion } from "framer-motion";
import { Megaphone, Search, Gauge, Sparkles, ArrowRight } from "lucide-react";
import Link from "next/link";

export default function FeatureCards() {
  const features = [
    {
      icon: Megaphone,
      title: "Facebook & Instagram Ads",
      badge: "Live Ad Spy",
      desc: "See all active photo and video ads your competitor is running right now. Check how many ads they run and their estimated monthly budget.",
      stats: "Live Photos & Video Ads",
      link: "/demo",
      accentGlow: "from-[#F0511F]/15 via-[#781E16]/10 to-transparent",
      iconBg: "bg-gradient-to-br from-[#F0511F]/20 to-[#781E16]/20 text-[#F0511F] border-[#F0511F]/30",
      badgeStyle: "bg-[var(--highlight-bg)] text-[#F0511F] border-[var(--highlight-border)]",
    },
    {
      icon: Search,
      title: "Google Search Ads",
      badge: "Keyword Spy",
      desc: "Find out if your competitor pays for Google search ads. Discover the exact search words they target and find high-profit keywords they missed.",
      stats: "Target Search Keywords",
      link: "/demo",
      accentGlow: "from-[#F58458]/15 via-[#F0511F]/10 to-transparent",
      iconBg: "bg-gradient-to-br from-[#F58458]/20 to-[#F0511F]/20 text-[#F58458] border-[#F58458]/30",
      badgeStyle: "bg-[#F58458]/10 text-[#F58458] border-[#F58458]/30",
    },
    {
      icon: Gauge,
      title: "Website Speed Test",
      badge: "Speed Check",
      desc: "Test how fast their website opens on mobile phones and computers. Slow websites lose customers — find where they are losing buyers.",
      stats: "Mobile & Computer Speed",
      link: "/demo",
      accentGlow: "from-[#FBCAAD]/15 via-[#F58458]/10 to-transparent",
      iconBg: "bg-gradient-to-br from-[#FBCAAD]/20 to-[#F58458]/20 text-[#FBCAAD] border-[#FBCAAD]/30",
      badgeStyle: "bg-[#FBCAAD]/10 text-[#FBCAAD] border-[#FBCAAD]/30",
    },
    {
      icon: Sparkles,
      title: "Smart AI Action Plan",
      badge: "AI Strategy",
      desc: "Get easy, step-by-step advice generated by AI. Learn their main strengths, big weaknesses, and exact steps you can take to beat them.",
      stats: "Step-by-Step Tips",
      link: "/demo",
      accentGlow: "from-[#F0511F]/20 via-[#FBCAAD]/10 to-transparent",
      iconBg: "bg-gradient-to-br from-[#F0511F]/25 to-[#FBCAAD]/20 text-[#F0511F] border-[#F0511F]/35",
      badgeStyle: "bg-[var(--highlight-bg)] text-[#F0511F] border-[var(--highlight-border)]",
    },
  ];

  return (
    <section id="features" className="py-16 md:py-24 bg-[var(--surface-subtle)] border-y border-[var(--border-theme)] relative transition-colors duration-300 overflow-hidden">
      {/* Subtle Background Radial Ambient Glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[400px] bg-gradient-to-r from-[#F0511F]/8 via-[#781E16]/5 to-transparent rounded-full blur-3xl pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto space-y-3 mb-14">
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[var(--highlight-bg)] border border-[var(--highlight-border)] text-xs font-bold uppercase tracking-wider text-[#F0511F]">
            <Sparkles className="w-3.5 h-3.5 text-[#F0511F]" />
            <span>What You Will Discover</span>
          </span>
          <h2 className="text-2xl sm:text-4xl font-extrabold font-heading text-[var(--text-primary)] tracking-tight">
            4 Powerful Tools to Grow Your Business Faster
          </h2>
          <p className="text-sm sm:text-base text-[var(--text-secondary)] leading-relaxed max-w-2xl mx-auto">
            Stop guessing what your rivals are doing. RankComp checks their live ads, Google keywords, and site speed so you can get more sales.
          </p>
        </div>

        {/* 4 Feature Highlight Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, idx) => {
            const Icon = feature.icon;
            return (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 25 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: idx * 0.1 }}
                className="relative bg-[var(--surface-card)] rounded-2xl p-6 sm:p-7 border border-[var(--border-theme)] hover:border-[#F0511F]/50 shadow-sm hover:shadow-xl hover:shadow-[#F0511F]/10 transition-all duration-300 flex flex-col justify-between group overflow-hidden"
              >
                {/* Top Subtle Hover Accent Bar */}
                <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-[#F0511F]/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />

                {/* Subtle Inner Glow on Hover */}
                <div
                  className={`absolute -top-16 -right-16 w-36 h-36 bg-gradient-to-br ${feature.accentGlow} rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none`}
                />

                <div className="relative z-10">
                  <div className="flex items-center justify-between mb-5">
                    <div
                      className={`w-12 h-12 rounded-xl flex items-center justify-center border shadow-xs transition-transform duration-300 group-hover:scale-105 ${feature.iconBg}`}
                    >
                      <Icon className="w-6 h-6" />
                    </div>
                    <span className={`text-[11px] font-bold px-2.5 py-1 rounded-full border ${feature.badgeStyle}`}>
                      {feature.badge}
                    </span>
                  </div>

                  <h3 className="text-lg font-bold font-heading text-[var(--text-primary)] group-hover:text-[#F0511F] transition-colors">
                    {feature.title}
                  </h3>

                  <p className="text-xs sm:text-sm text-[var(--text-secondary)] mt-2.5 leading-relaxed">
                    {feature.desc}
                  </p>
                </div>

                <div className="relative z-10 pt-5 mt-5 border-t border-[var(--border-theme)] flex items-center justify-between text-xs font-semibold">
                  <span className="text-[#F0511F] font-bold text-[11px]">{feature.stats}</span>
                  <Link
                    href={feature.link}
                    className="inline-flex items-center gap-1 text-[var(--text-secondary)] group-hover:text-[#F0511F] group-hover:translate-x-1 transition-all"
                  >
                    <span>See Example</span>
                    <ArrowRight className="w-3 h-3" />
                  </Link>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
